### ISSUE TITLE
BARF Comparison in the Demo

### ISSUE THREAD

**Issue by GloryyrolG** [Nemo1999/Bundle_Adjusting_TensoRF#1]
Hi @Nemo1999 @chenhsuanlin @szymanowiczs @martinarroyo et al.,

May I ask what the diff between BARF in the demo & the original BARF? Cuz I found my BARF takes > 50K iters to obtain a reasonable rendering. Thx & rgds,

![image](https://github.com/Nemo1999/Joint-TensoRF/assets/33202229/7424aa02-f4fa-44d4-bda3-7f0808347499)

**Comment by Nemo1999** [comment]
Hi, for BARF we need to run 200k for complete result.
